# fly.toml app configuration file generated for ledger-iljhaa on 2025-05-13T20:42:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ledger-iljhaa'
primary_region = 'yul'

[build]
  [build.args]
    GO_VERSION = '1.23.0'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'false'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
